name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node version
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          npm install
          
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
      
      - name: Generate SBOM file
        uses: CycloneDX/gh-node-module-generatebom@master
  
      - name: Get secrets
        run: |
          echo "Getting short commit and repo name..."
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo ${REPO_NAME}
          echo "Repo name: ...."
          echo ${REPO_NAME}
      
      - name: Run dependency tracker
        uses: attempto-Lab/dependencytrackupload-github-action@v1
        with:
          serverUrl: 'https://pretty-clam-romantic.ngrok-free.app/api/v1/bom'
          apiKey: "odt_yPbW456wU3sDsAXRkzi1b07avSYAE2Es"
          bomFile: 'bom.xml'
          projectName: ${{ env.REPO_NAME }}
          projectVersion: ${{ env.SHORT_SHA }}
          autoCreate: true
    
  # generate-upload-sbom:
    # runs-on: ubuntu-latest
    # needs: build-scan
    # steps:  
    #   - uses: actions/checkout@v3

    #   - name: Generate SBOM file
    #     uses: CycloneDX/gh-node-module-generatebom@master

    #   - name: Get secrets
    #     run: |
    #       echo "Getting short commit and repo name..."
    #       echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
    #       echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    #       echo ${REPO_NAME}
    #       echo "Repo name: ...."
    #       echo ${REPO_NAME}
      
    #   - name: Run dependency tracker
    #     uses: attempto-Lab/dependencytrackupload-github-action@v1
    #     with:
    #       serverUrl: 'https://pretty-clam-romantic.ngrok-free.app/api/v1/bom'
    #       apiKey: "odt_yPbW456wU3sDsAXRkzi1b07avSYAE2Es"
    #       bomFile: 'bom.xml'
    #       projectName: ${{ env.REPO_NAME }}
    #       projectVersion: ${{ env.SHORT_SHA }}
    #       autoCreate: true
