name: Dependency Tracker

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build-sbom-scan-monitoring:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node version
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"


      - name: Install dependencies
        run: |
          npm install
          echo "Getting short commit..."
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Generate SBOM file
        uses: CycloneDX/gh-node-module-generatebom@master

      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0
        with:
          with-owner: 'true'
          string-case: 'lowercase'

      - name: Run dependency tracker

        uses: attempto-Lab/dependencytrackupload-github-action@v1
        with:
          serverUrl: 'https://pretty-clam-romantic.ngrok-free.app/api/v1/bom'
          apiKey: "odt_yPbW456wU3sDsAXRkzi1b07avSYAE2Es"
          bomFile: 'bom.xml'
          projectName: ${{ steps.repo-name.outputs.repository-name }}
          projectVersion: ${SHORT_SHA}
          autoCreate: true
